package:
  name: cptdl
  version: "1.1.0"

source:
  path: ..

build:
  number: 0
  noarch: python

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - xarray
    - cptio
    - requests

test:
  imports:
    - cptdl



about:
  home: https://github.com/iri-pycpt/
  license: MIT
  summary: 'toolkit bridging the gap between CPT and Xarray'
  description: 'IRI DL Downloads'
  dev_url: https://github.com/iri-pycpt/
